# Generated by Django 3.2.9 on 2021-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211125_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to=''),
        ),
    ]
