# Generated by Django 3.2.9 on 2021-11-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211128_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pos_ratio', '-vote_total', '-created']},
        ),
    ]
